### ISSUE TITLE
kmer questions

### ISSUE THREAD

**Issue by mictadlo** [bioinfologics/w2rap#8]
Hi,
Do you think it would be a good idea:
* to use any of [khmer](https://khmer-recipes.readthedocs.io/en/latest/) recipes and 
* to use [kmergenie](http://kmergenie.bx.psu.edu) in order to determine `-K` parameter.

Thank you in advance

Michal

**Comment by jonwright99** [comment]
Answered in https://github.com/bioinfologics/w2rap-contigger/issues/36
